[tools]
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"aqua:mitsuhiko/insta" = "latest"
"aqua:taiki-e/cargo-llvm-cov" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:flamegraph" = "latest"
prek = "latest"
just = "latest"
